services:
  frontend:
    image: autoboxex-vue:1.0.0
    container_name: autoboxex-frontend
    ports:
      - 80:80
    networks:
      - autoboxex-network
  backend:
    image: autoboxex-laravel:1.0.1
    container_name: autoboxex-backend
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - autoboxex-network
networks:
  autoboxex-network:
    driver: bridge
name: autoboxex