services:
  web:
    image: autoboxex:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    networks:
      - backend
  # database:
  #   container_name: mssql-db
  #   hostname: mssql-db
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     ACCEPT_EULA: 'Y'
  #     MSSQL_SA_PASSWORD: 'Passw0rd'
  #     MSSQL_DATA_DIR: /var/opt/mssql/data
  #     MSSQL_PID: 'Developer' 
  #     MSSQL_TCP_PORT: 1433 
  #   ports: 
  #     - 1433:1433
  #   volumes:
  #     - my-db:/var/opt/mssql/data
  #   networks:
  #     - backend