services:
  web:
    image: autoboxex:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    networks:
      - backend
  database:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
volumes:
  my-db:

networks:
  backend: